Sign up
LeandroNz/Digital_Bank pull request #5
Opened 2022-03-10 15:41 UTC by LeandroNz

2022-03-10 19:31 UTC, rquintana-abstracta commented on pages/signup.page.js
> +        }
You can simplify this into a one-liner using the **ternary operator**, and the fact that currently you have only 2 genders to choose from:

```javascript

radioBtn == 'M' ? await super.clickOnElement(this.radioM) : await super.clickOnElement(this.radioF);
```

Ref: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Conditional_Operator

2022-03-10 19:35 UTC, rquintana-abstracta commented on tests/signup.test.js
> +    INVALIDINPUTFIRSTFORM.forEach(({title, firstName, lastName, Gender, dob, ssn, email, passwd, confirmPasswd, reason}) => {
naming convention in JS for everything except classes and constants is camelCase. Gender is capitalized. Make sure to lower case it everywhere to comply with conventions.

2022-03-10 19:36 UTC, rquintana-abstracta commented on tests/signup.test.js
> +      await LoginPage.goToSignupPage();
This test doesnt have an assertion, so it's incomplete. Make sure to add one to it

2022-03-10 19:37 UTC, rquintana-abstracta commented on tests/signup.test.js
> +      await SignUpPage.inputFirstForm(1, "a", "b", 'M', "11/01/2001", "848-45-6789", "prueba@gmail.com", "Demo123!", "Demo123!");
Same comment than before, add an assertion to the test to complete it.

2022-03-10 19:38 UTC, rquintana-abstracta commented on tests/signup.test.js
> +          await expect(await LoginPage.successMsg).not.toBeDisplayed();
the inner await inside the `expect()` function is not really needed, as wdio takes care of everything inside it (including call modifiers, like await in this case) when using a native matcher, like you are using in this case

2022-03-10 19:39 UTC, rquintana-abstracta commented on pages/base.page.js
> +   async refreshBrowser() {
I assume you had a need to use it because you were not using a beforeEach hook making sure you login for every new test. Consider removing this, if that's the case

2022-03-10 19:40 UTC, rquintana-abstracta commented on tests/signup.test.js
> +});
Update test cases doc for these new tests

2022-03-10 19:41 UTC, rquintana-abstracta requested changes
Implement requested changes

2022-03-10 21:01 UTC, LeandroNz commented on pages/signup.page.js
> +        }
A ternary operator cannot be used as it cannot consider the case were both of the radio buttons are left unchecked, which is one of the test cases implemented in this module.

2022-03-11 21:19 UTC, rquintana-abstracta commented on pages/signup.page.js
> +        }
Fair point :)

2022-03-11 21:24 UTC, rquintana-abstracta approved these changes

2022-03-12 15:30 UTC, merged